[postgres]
host = "127.0.0.1"
dbname = "studentdb"
user = "student"
password = "student"

[filenames]
immigration_description = "data/I94_SAS_Labels_Descriptions.SAS"
immigration = "data/immigration_full/i94_apr16_sub.parquet"
temperatures = "data/GlobalLandTemperaturesByCity.csv"
demographics = "data/us-cities-demographics.csv"
state_demographics = "data/us_demographics_by_state.csv"